#!/bin/bash
# Credential store helper that uses the `pass` software on linux to read/write git credentials

orig_IFS=${IFS}

usage() {
	echo "Usage:"
	echo
	echo "  git-credential-helper-pass <get|store|erase>"
	IFS=${orig_IFS}
	exit 1;
}

if [[ "$#" -ne 1 ]]; then
	usage;
fi

if [[ "$1" == "store" ]]; then
	IFS="="
	read d1 protocol
	read d2 hostname
	read d3 user
	read d4 password
	IFS="${orig_IFS}"
	echo -e "protocol=${protocol}\nhost=${hostname}\nusername=${user}\npassword=${password}" | pass insert -m git/${protocol}/${hostname}
fi

if [[ "$1" == "get" ]]; then
	IFS="="
	read d1 protocol
	read d2 hostname
	IFS=${orig_IFS}
	pass git/${protocol}/${hostname}
fi
