#!/bin/bash

find ./ | grep -i --color=always "$1" 2>/dev/null | tee /tmp/fstr_search | less -R -F -X

chr=$(echo -e "\033")

options=$(cat /tmp/fstr_search | sed -e 's/'${chr}'\[[0-9;]*m//g' -e 's/'${chr}'\[K//g' -e 's/^\.\///' -e '/^Binary file/d' | uniq | sort)

echo "${options}" > /tmp/fstr_options
